name: Taksi
version: '${project.version}'
main: com.jeffe.taksi
api-version: 1.18
authors: [ JEFFe ]
description: Taksita himaa
website: https://jeffe.co

commands:
  taksi:
    description: Taksita himaa
    usage: /taksi Jarkkovammainen
  gn:
    description: Nukuttaako?
    usage: /gn kloppi
#  hima:
#    description: uusi hima?
#    usage: /hima
  sadevittuun:
    description: sade pois?
    usage: /sadevittuun
  lagaanko:
    description: lagaako servu?
    usage: /lagaanko
